- name: Install 1c components
  hosts: all
  
  tasks:
  - name: Install 1c
    install_1c: 
        path: /home/nails/setup-full-8.3.20.1710-x86_64.run
        components:
          - config_storage_server
          - integrity_monitoring
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'

